#!/bin/sh

case $(file --mime-type "$1" -bL) in

	video/* | audio/*)
		mpv "$@"
		;;

	application/pdf |\
	application/postscript |\
	application/x-mobipocket-ebook |\
	application/epub+zip |\
	image/vnd.djvu)
		zathura "$@"
		;;

	image/*)
		sxiv "$@"
		;;

	application/msword |\
	application/vnd.ms-powerpoint)
		libreoffice "$@"
		;;

	text/*)
		nvim "$@"
		;;

	*)
		echo "File type '$(file --mime-type "$1" -bL)' not support!" >&2
		exit 1
		;;
esac
